controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_like_post:
    path: '/O-eeffoc/like-post/{id}'
    controller: 'App\Controller\LikeController::likePost'
